Chainlink 24: make rider list visible to all riders not just the creator
LearnDialogue/CyclingMatchmaker-Client pull request #7
Opened 2024-09-28 00:42 UTC by Alec8888

https://heartratehackers.atlassian.net/browse/CHAINLINK-24?atlOrigin=eyJpIjoiMjFhMmI5Mzk0MGIyNGM5NWE0NDFlZGExYTViY2EyZjQiLCJwIjoiaiJ9

2024-09-28 18:29 UTC, bakermo requested changes

2024-09-28 18:29 UTC, bakermo commented on src/routes/app/RidesFeed.tsx
The rider list stuff looks good, approved.  But the RidesFeed stuff for gender shouldn't be here, I'm guessing you branched off of your previous branch here instead of main.

2024-10-01 21:55 UTC, Alec8888 commented on src/routes/app/RidesFeed.tsx
ok I fixed it, ready for review and merge

2024-10-01 23:02 UTC, bakermo approved these changes

2024-10-01 23:02 UTC, merged